server {
    listen 80;
    server_name localhost;

    # upstream bookings_service {
    #     server bookings-service:3003;
    # }

    location /api/bookings {
        proxy_pass http://bookings-service:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
    }
    # location /health {
    #         return 200 '{"status": "healthy", "timestamp": "'"$(date +%s)"'"}';
    #         add_header Content-Type application/json;
    #     }
}