server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Frontend (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # # API proxy
    # location /api/ {
    #     proxy_pass http://api-gateway:80;
    # }
}
